# Generated by Django 3.2 on 2021-04-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1000)),
                ('built_in', models.CharField(max_length=128)),
                ('accuracy', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.CharField(max_length=400)),
                ('predicted_sentiment', models.CharField(max_length=10)),
                ('answer_probability', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentimentAI.ai_model')),
            ],
        ),
    ]
